spring:
  security:
    user:
      name: root
      password: root
  application:
    name: citi
  datasource:
    url: jdbc:postgresql://localhost:5432/microservice
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always
      platform: postgres


logging:
  level:
    root: debug

server:
  port: 8080